<form method="post" action="index.php">
    <fieldset>
        <label for="firstName">First Name</label>
        <input type="text" name="firstName"/>
    </fieldset>
    <fieldset>
        <label for="lastName">Last Name</label>
        <input type="text" name="lastName"/>
    </fieldset>
    <fieldset>
        <label for="email">Email</label>
        <input type="email" name="email"/>
    </fieldset>
    <fieldset>
        <label for="password">Mot de passe</label>
        <input type="password" name="password"/>
    </fieldset>
    <fieldset>
        <label for="confirm-pwd">Confirmer le mot de passe</label>
        <input type="password" name="confirm-pwd"/>
    </fieldset>
    <fieldset>
        <input type="submit" name="submit" value="S'enregistrer"/>
    </fieldset>
    <input type="hidden" name="formName"/>
</form>

